name: oohapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  connectivity_plus: ^6.0.1
  intl: ^0.19.0
  table_calendar: ^3.0.0-nullsafety.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  universal_html: ^2.2.4
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  pin_code_fields: ^8.0.1
  google_nav_bar: ^5.0.6
  dot_navigation_bar: ^1.0.2
  custom_navigation_bar: ^0.8.2
  syncfusion_flutter_charts: ^25.1.35
  image_picker: ^1.0.6
  google_maps_flutter: ^2.5.2
  dotted_border: ^2.1.0
  syncfusion_flutter_datepicker: ^25.1.35
  equatable: ^2.0.5
  email_validator: ^2.1.17
  country_list: ^0.0.5
  carousel_slider: ^4.2.1
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  timeline_tile: ^2.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
