List<Map<String, dynamic>> oohHoardingDummyData = [
  {
    'imageUrl':
    'https://cdn.photofunia.com/effects/nyc_billboards/examples/fg19ln_o.jpg',
    'hoardingLocation': 'Polytechnic Circle',
    'hoardingCity': 'Gomati nagar',
    'hoardingPrice': '12,000',
    'month': 'month',
    'discountPrice': '9500',
    'ratingText': '4.3',
    'numberOfImage': "1/6",
    'hoardingType': 'Unipole - OOH',
  },
  {
    'imageUrl':
    'https://www.timessquarenyc.org/sites/default/files/body-images/Digital-Screens-Branded-Cities-Nasdaq.jpg',
    'hoardingLocation': 'Hazratganj Circle',
    'hoardingCity': 'Lucknow',
    'hoardingPrice': '12,000',
    'month': 'month',
    'discountPrice': '5400',
    'ratingText': '4.2',
    'numberOfImage': "1/6",
    'hoardingType': 'Unipole - OOH',
  },
  {
    'imageUrl':
    'https://inspiriaoutdoor.com/wp-content/uploads/2021/03/Times-Square-Nasdaq-Digital-Billboard-Advertising-GTP-Jewellery-Limited-Campaign-910x619.jpg',
    'hoardingLocation': 'Charbagh Station',
    'hoardingCity': 'Gomati nagar',
    'hoardingPrice': '12,000',
    'month': 'month',
    'discountPrice': '8600',
    'ratingText': '4.9',
    'numberOfImage': "1/6",
    'hoardingType': 'Unipole - OOH',
  },
  {
    'imageUrl': 'https://pbs.twimg.com/media/DFoNA2VVoAANfxl.jpg:large',
    'hoardingLocation': 'Awadh bus stand',
    'hoardingCity': 'Indira nagar',
    'hoardingPrice': '12,000',
    'month': 'month',
    'discountPrice': '3000',
    'ratingText': '4.5',
    'numberOfImage': "1/6",
    'hoardingType': 'Unipole - OOH',
  },
];



List<Map<String, dynamic>> doohHoardingDummyData = [
  {
    'imageUrl':
    'https://images.unsplash.com/photo-1710604755847-1a6b8ddb7d89?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'hoardingLocation': 'Polytechnic Circle',
    'hoardingCity': 'Gomati nagar',
    'hoardingPrice': '12,000',
    'month': 'month',
    'discountPrice': '9500',
    'ratingText': '4.3',
    'numberOfImage': "1/6",
    'hoardingType': 'Unipole - DOOH',
  },
  {
    'imageUrl':
    'https://images.unsplash.com/photo-1680178441861-c9539e92434f?q=80&w=2116&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'hoardingLocation': 'Hazratganj Circle',
    'hoardingCity': 'Lucknow',
    'hoardingPrice': '12,000',
    'month': 'month',
    'discountPrice': '5400',
    'ratingText': '4.2',
    'numberOfImage': "1/6",
    'hoardingType': 'Unipole - DOOH',
  },
  {
    'imageUrl':
    'https://images.unsplash.com/photo-1662714201491-56bdd45aa7f8?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'hoardingLocation': 'Charbagh Station',
    'hoardingCity': 'Gomati nagar',
    'hoardingPrice': '12,000',
    'month': 'month',
    'discountPrice': '8600',
    'ratingText': '4.9',
    'numberOfImage': "1/6",
    'hoardingType': 'Unipole - DOOH',
  },
  {
    'imageUrl': 'https://images.unsplash.com/photo-1662714197841-6357ac257e60?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'hoardingLocation': 'Awadh bus stand',
    'hoardingCity': 'Indira nagar',
    'hoardingPrice': '12,000',
    'month': 'month',
    'discountPrice': '3000',
    'ratingText': '4.5',
    'numberOfImage': "1/6",
    'hoardingType': 'Unipole - DOOH',
  },{
    'imageUrl': 'https://images.unsplash.com/photo-1616418625172-c607e16733ca?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'hoardingLocation': 'Charbagh bus stand',
    'hoardingCity': 'Bootnath Market',
    'hoardingPrice': '19,000',
    'month': 'month',
    'discountPrice': '3000',
    'ratingText': '5.0',
    'numberOfImage': "1/6",
    'hoardingType': 'Unipole - DOOH',
  },{
    'imageUrl': 'https://images.unsplash.com/photo-1575495662727-2274506f4599?q=80&w=2127&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'hoardingLocation': 'Alambagh bus stand',
    'hoardingCity': 'Krishna nagar',
    'hoardingPrice': '12,000',
    'month': 'month',
    'discountPrice': '6531',
    'ratingText': '3.5',
    'numberOfImage': "1/6",
    'hoardingType': 'Unipole - DOOH',
  },{
    'imageUrl': 'https://images.unsplash.com/photo-1623189831691-601692d33879?q=80&w=2030&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'hoardingLocation': 'Alambagh bus stand',
    'hoardingCity': 'Alambagh',
    'hoardingPrice': '32,000',
    'month': 'month',
    'discountPrice': '2000',
    'ratingText': '2.5',
    'numberOfImage': "1/6",
    'hoardingType': 'Unipole - DOOH',
  },
];